version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/prod/Dockerfile
      tags:
        - "helixow/guess-the-color"
    container_name: guess-the-color
    ports:
      - "443:443"