version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/test/Dockerfile
      tags:
        - "helixow/guess-the-color"
    container_name: guess-the-color
    ports:
      - "80:80"