name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: helixow
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    - name: Install angular cli
      run: npm install -g @angular/cli
    - name: Install node modules
      run: npm install
    - name: Build angular app
      run: ng build
    - name: Build the images
      run: docker compose -f docker-compose-prod.yml create
    - name: Publish the image
      run: docker push helixow/guess-the-color
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Kingbot.eu
      uses: appleboy/ssh-action@master
      with:
        host: kingbot.eu
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          docker pull helixow/guess-the-color
          cd /root/guess-the-color
          docker compose up -d
